version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: movie_catalog
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5432:5432

  cache:
    image: redis
    restart: always
    ports:
      - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
    environment:
      POSTGRES_URL: postgres://local:password@db:5432/movie_catalog
      REDIS_URL: redis://cache:6379
    env_file:
      - .env
    command: npm run start:dev
    restart: always
volumes:
  db_data:
