version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
    environment:
      POSTGRES_URL: postgres://myuser:mypassword@db:5432/mydatabase
      REDIS_URL: redis://cache:6379
    command: npm run start:dev
    restart: always

volumes:
  db_data: